// Package client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package client

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for ProviderType.
const (
	ProviderTypeExternal         ProviderType = "external"
	ProviderTypeKeycardDirectory ProviderType = "keycard-directory"
	ProviderTypeKeycardVault     ProviderType = "keycard-vault"
)

// Defines values for ListProvidersParamsType0.
const (
	ListProvidersParamsType0External ListProvidersParamsType0 = "external"
)

// Defines values for ListProvidersParamsType1.
const (
	KeycardVault ListProvidersParamsType1 = "keycard-vault"
)

// Defines values for ListProvidersParamsType2.
const (
	KeycardDirectory ListProvidersParamsType2 = "keycard-directory"
)

// Error Error response
type Error struct {
	Code    string  `json:"code"`
	Message string  `json:"message"`
	Status  float32 `json:"status"`
}

// PageInfo Pagination information
type PageInfo struct {
	// EndCursor Cursor pointing to the last item in the current page
	EndCursor *string `json:"end_cursor"`

	// HasNextPage Whether there are more items after the current page
	HasNextPage bool `json:"has_next_page"`

	// HasPreviousPage Whether there are items before the current page
	HasPreviousPage bool `json:"has_previous_page"`

	// StartCursor Cursor pointing to the first item in the current page
	StartCursor *string `json:"start_cursor"`
}

// Provider A Provider is a system that supplies access to Resources and allows actors (Users or Applications) to authenticate.
type Provider struct {
	// ClientId OAuth 2.0 client identifier
	ClientId *string `json:"client_id"`

	// ClientSecretSet Indicates whether a client secret is configured
	ClientSecretSet *bool `json:"client_secret_set,omitempty"`

	// CreatedAt Entity creation timestamp
	CreatedAt time.Time `json:"created_at"`

	// Description Human-readable description
	Description *string `json:"description"`

	// Id Unique identifier of the provider
	Id string `json:"id"`

	// Identifier User specified identifier, unique within the zone
	Identifier string `json:"identifier"`

	// Name Human-readable name
	Name string `json:"name"`

	// OrganizationId Organization that owns this provider
	OrganizationId string `json:"organization_id"`

	// Protocols Protocol-specific configuration
	Protocols *struct {
		// Oauth2 OAuth 2.0 / OpenID Connect protocol configuration
		Oauth2 *struct {
			AuthorizationEndpoint         *string   `json:"authorization_endpoint"`
			CodeChallengeMethodsSupported *[]string `json:"code_challenge_methods_supported"`
			JwksUri                       *string   `json:"jwks_uri"`
			RegistrationEndpoint          *string   `json:"registration_endpoint"`
			ScopesSupported               *[]string `json:"scopes_supported"`
			TokenEndpoint                 *string   `json:"token_endpoint"`
			UserinfoEndpoint              *string   `json:"userinfo_endpoint"`
		} `json:"oauth2"`
	} `json:"protocols"`

	// Slug URL-safe identifier, unique within the zone
	Slug string        `json:"slug"`
	Type *ProviderType `json:"type,omitempty"`

	// UpdatedAt Entity update timestamp
	UpdatedAt time.Time `json:"updated_at"`

	// ZoneId Zone this provider belongs to
	ZoneId string `json:"zone_id"`
}

// ProviderType defines model for Provider.Type.
type ProviderType string

// ProviderCreate Schema for creating a new provider
type ProviderCreate struct {
	// ClientId OAuth 2.0 client identifier
	ClientId *string `json:"client_id,omitempty"`

	// ClientSecret OAuth 2.0 client secret (will be encrypted and stored securely)
	ClientSecret *string `json:"client_secret,omitempty"`

	// Description Human-readable description
	Description *string `json:"description"`

	// Identifier User specified identifier, unique within the zone
	Identifier string `json:"identifier"`

	// Name Human-readable name
	Name string `json:"name"`

	// Protocols Protocol-specific configuration
	Protocols *struct {
		// Oauth2 OAuth 2.0 / OpenID Connect protocol configuration
		Oauth2 *struct {
			AuthorizationEndpoint         *string   `json:"authorization_endpoint,omitempty"`
			CodeChallengeMethodsSupported *[]string `json:"code_challenge_methods_supported,omitempty"`
			JwksUri                       *string   `json:"jwks_uri,omitempty"`
			RegistrationEndpoint          *string   `json:"registration_endpoint,omitempty"`
			ScopesSupported               *[]string `json:"scopes_supported,omitempty"`
			TokenEndpoint                 *string   `json:"token_endpoint,omitempty"`
			UserinfoEndpoint              *string   `json:"userinfo_endpoint,omitempty"`
		} `json:"oauth2,omitempty"`
	} `json:"protocols,omitempty"`
}

// ProviderUpdate Schema for updating an existing provider
type ProviderUpdate struct {
	// ClientId OAuth 2.0 client identifier. Set to null to remove.
	ClientId *string `json:"client_id"`

	// ClientSecret OAuth 2.0 client secret (will be encrypted and stored securely). Set to null to remove.
	ClientSecret *string `json:"client_secret"`

	// Description Human-readable description
	Description *string `json:"description"`

	// Identifier User specified identifier, unique within the zone
	Identifier *string `json:"identifier,omitempty"`

	// Name Human-readable name
	Name *string `json:"name,omitempty"`

	// Protocols Protocol-specific configuration. Set to null to remove all protocols.
	Protocols *struct {
		// Oauth2 OAuth 2.0 protocol configuration. Set to null to remove all OAuth2 config.
		Oauth2 *struct {
			AuthorizationEndpoint         *string   `json:"authorization_endpoint"`
			CodeChallengeMethodsSupported *[]string `json:"code_challenge_methods_supported"`
			JwksUri                       *string   `json:"jwks_uri"`
			RegistrationEndpoint          *string   `json:"registration_endpoint"`
			ScopesSupported               *[]string `json:"scopes_supported"`
			TokenEndpoint                 *string   `json:"token_endpoint"`
		} `json:"oauth2"`

		// Openid OpenID Connect protocol configuration. Set to null to remove all OpenID config.
		Openid *struct {
			UserinfoEndpoint *string `json:"userinfo_endpoint"`
		} `json:"openid"`
	} `json:"protocols"`
}

// Zone A zone for organizing resources within an organization
type Zone struct {
	// Cname Custom domain name (CNAME) for the zone
	Cname *string `json:"cname,omitempty"`

	// CreatedAt Entity creation timestamp
	CreatedAt time.Time `json:"created_at"`

	// Description Human-readable description
	Description *string `json:"description"`

	// Id Unique identifier of the zone
	Id string `json:"id"`

	// Name Human-readable name
	Name string `json:"name"`

	// Oauth2DcrEnabled Whether Dynamic Client Registration is enabled
	Oauth2DcrEnabled bool `json:"oauth2_dcr_enabled"`

	// Oauth2PkceRequired Whether PKCE is required for authorization code flows
	Oauth2PkceRequired bool `json:"oauth2_pkce_required"`

	// OrganizationId Organization that owns this zone
	OrganizationId string `json:"organization_id"`
	Protocols      struct {
		Oauth2 struct {
			// AuthorizationEndpoint OAuth 2.0 authorization endpoint
			AuthorizationEndpoint string `json:"authorization_endpoint"`

			// AuthorizationServerMetadata OAuth 2.0 Authorization Server Metadata endpoint (.well-known/oauth-authorization-server)
			AuthorizationServerMetadata string `json:"authorization_server_metadata"`

			// Issuer OAuth 2.0 issuer identifier
			Issuer string `json:"issuer"`

			// JwksUri JSON Web Key Set endpoint
			JwksUri string `json:"jwks_uri"`

			// RedirectUri OAuth 2.0 redirect URI for this zone
			RedirectUri string `json:"redirect_uri"`

			// RegistrationEndpoint OAuth 2.0 Dynamic Client Registration endpoint
			RegistrationEndpoint string `json:"registration_endpoint"`

			// TokenEndpoint OAuth 2.0 token endpoint
			TokenEndpoint string `json:"token_endpoint"`
		} `json:"oauth2"`
		Openid struct {
			// ProviderConfiguration OpenID Connect Provider Configuration endpoint (.well-known/openid-configuration)
			ProviderConfiguration string `json:"provider_configuration"`

			// UserinfoEndpoint OpenID Connect UserInfo endpoint
			UserinfoEndpoint string `json:"userinfo_endpoint"`
		} `json:"openid"`
	} `json:"protocols"`

	// Slug URL-safe identifier, unique within the zone
	Slug string `json:"slug"`

	// UpdatedAt Entity update timestamp
	UpdatedAt time.Time `json:"updated_at"`

	// UserIdentityProviderId Provider ID configured for user login
	UserIdentityProviderId *string `json:"user_identity_provider_id,omitempty"`
}

// ZoneCreate Schema for creating a new zone
type ZoneCreate struct {
	// Cname Custom domain name (CNAME) for the zone
	Cname *string `json:"cname,omitempty"`

	// Description Human-readable description
	Description *string `json:"description"`

	// Name Human-readable name
	Name string `json:"name"`

	// Oauth2DcrEnabled Whether Dynamic Client Registration is enabled
	Oauth2DcrEnabled *bool `json:"oauth2_dcr_enabled,omitempty"`

	// Oauth2PkceRequired Whether PKCE is required for authorization code flows
	Oauth2PkceRequired *bool `json:"oauth2_pkce_required,omitempty"`
}

// ZoneUpdate Schema for updating an existing zone (partial update)
type ZoneUpdate struct {
	// Cname Custom domain name (CNAME) for the zone (set to null to remove)
	Cname *string `json:"cname"`

	// Description Human-readable description
	Description *string `json:"description"`

	// Name Human-readable name
	Name *string `json:"name,omitempty"`

	// Oauth2DcrEnabled Whether Dynamic Client Registration is enabled
	Oauth2DcrEnabled *bool `json:"oauth2_dcr_enabled,omitempty"`

	// Oauth2PkceRequired Whether PKCE is required for authorization code flows
	Oauth2PkceRequired *bool `json:"oauth2_pkce_required,omitempty"`

	// UserIdentityProviderId Provider ID to configure for user login (set to null to unset)
	UserIdentityProviderId *string `json:"user_identity_provider_id"`
}

// ListZonesParams defines parameters for ListZones.
type ListZonesParams struct {
	Slug   *string `form:"slug,omitempty" json:"slug,omitempty"`
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListProvidersParams defines parameters for ListProviders.
type ListProvidersParams struct {
	Slug       *string `form:"slug,omitempty" json:"slug,omitempty"`
	Identifier *string `form:"identifier,omitempty" json:"identifier,omitempty"`
	Type       *struct {
		union json.RawMessage
	} `form:"type,omitempty" json:"type,omitempty"`
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListProvidersParamsType0 defines parameters for ListProviders.
type ListProvidersParamsType0 string

// ListProvidersParamsType1 defines parameters for ListProviders.
type ListProvidersParamsType1 string

// ListProvidersParamsType2 defines parameters for ListProviders.
type ListProvidersParamsType2 string

// CreateZoneJSONRequestBody defines body for CreateZone for application/json ContentType.
type CreateZoneJSONRequestBody = ZoneCreate

// UpdateZoneJSONRequestBody defines body for UpdateZone for application/json ContentType.
type UpdateZoneJSONRequestBody = ZoneUpdate

// CreateProviderJSONRequestBody defines body for CreateProvider for application/json ContentType.
type CreateProviderJSONRequestBody = ProviderCreate

// UpdateProviderJSONRequestBody defines body for UpdateProvider for application/json ContentType.
type UpdateProviderJSONRequestBody = ProviderUpdate

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ListZones request
	ListZones(ctx context.Context, params *ListZonesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateZoneWithBody request with any body
	CreateZoneWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateZone(ctx context.Context, body CreateZoneJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteZone request
	DeleteZone(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetZone request
	GetZone(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateZoneWithBody request with any body
	UpdateZoneWithBody(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	UpdateZone(ctx context.Context, id string, body UpdateZoneJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListProviders request
	ListProviders(ctx context.Context, zoneId string, params *ListProvidersParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateProviderWithBody request with any body
	CreateProviderWithBody(ctx context.Context, zoneId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateProvider(ctx context.Context, zoneId string, body CreateProviderJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteProvider request
	DeleteProvider(ctx context.Context, zoneId string, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetProvider request
	GetProvider(ctx context.Context, zoneId string, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateProviderWithBody request with any body
	UpdateProviderWithBody(ctx context.Context, zoneId string, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	UpdateProvider(ctx context.Context, zoneId string, id string, body UpdateProviderJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ListZones(ctx context.Context, params *ListZonesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListZonesRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateZoneWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateZoneRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateZone(ctx context.Context, body CreateZoneJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateZoneRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteZone(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteZoneRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetZone(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetZoneRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateZoneWithBody(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateZoneRequestWithBody(c.Server, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateZone(ctx context.Context, id string, body UpdateZoneJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateZoneRequest(c.Server, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListProviders(ctx context.Context, zoneId string, params *ListProvidersParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListProvidersRequest(c.Server, zoneId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateProviderWithBody(ctx context.Context, zoneId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateProviderRequestWithBody(c.Server, zoneId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateProvider(ctx context.Context, zoneId string, body CreateProviderJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateProviderRequest(c.Server, zoneId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteProvider(ctx context.Context, zoneId string, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteProviderRequest(c.Server, zoneId, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetProvider(ctx context.Context, zoneId string, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetProviderRequest(c.Server, zoneId, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateProviderWithBody(ctx context.Context, zoneId string, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateProviderRequestWithBody(c.Server, zoneId, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateProvider(ctx context.Context, zoneId string, id string, body UpdateProviderJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateProviderRequest(c.Server, zoneId, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListZonesRequest generates requests for ListZones
func NewListZonesRequest(server string, params *ListZonesParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/zones")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Slug != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "slug", runtime.ParamLocationQuery, *params.Slug); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Cursor != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "cursor", runtime.ParamLocationQuery, *params.Cursor); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateZoneRequest calls the generic CreateZone builder with application/json body
func NewCreateZoneRequest(server string, body CreateZoneJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateZoneRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateZoneRequestWithBody generates requests for CreateZone with any type of body
func NewCreateZoneRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/zones")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteZoneRequest generates requests for DeleteZone
func NewDeleteZoneRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/zones/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetZoneRequest generates requests for GetZone
func NewGetZoneRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/zones/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUpdateZoneRequest calls the generic UpdateZone builder with application/json body
func NewUpdateZoneRequest(server string, id string, body UpdateZoneJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpdateZoneRequestWithBody(server, id, "application/json", bodyReader)
}

// NewUpdateZoneRequestWithBody generates requests for UpdateZone with any type of body
func NewUpdateZoneRequestWithBody(server string, id string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/zones/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PATCH", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewListProvidersRequest generates requests for ListProviders
func NewListProvidersRequest(server string, zoneId string, params *ListProvidersParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "zoneId", runtime.ParamLocationPath, zoneId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/zones/%s/providers", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Slug != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "slug", runtime.ParamLocationQuery, *params.Slug); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Identifier != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "identifier", runtime.ParamLocationQuery, *params.Identifier); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Type != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "type", runtime.ParamLocationQuery, *params.Type); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Cursor != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "cursor", runtime.ParamLocationQuery, *params.Cursor); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateProviderRequest calls the generic CreateProvider builder with application/json body
func NewCreateProviderRequest(server string, zoneId string, body CreateProviderJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateProviderRequestWithBody(server, zoneId, "application/json", bodyReader)
}

// NewCreateProviderRequestWithBody generates requests for CreateProvider with any type of body
func NewCreateProviderRequestWithBody(server string, zoneId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "zoneId", runtime.ParamLocationPath, zoneId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/zones/%s/providers", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteProviderRequest generates requests for DeleteProvider
func NewDeleteProviderRequest(server string, zoneId string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "zoneId", runtime.ParamLocationPath, zoneId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/zones/%s/providers/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetProviderRequest generates requests for GetProvider
func NewGetProviderRequest(server string, zoneId string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "zoneId", runtime.ParamLocationPath, zoneId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/zones/%s/providers/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUpdateProviderRequest calls the generic UpdateProvider builder with application/json body
func NewUpdateProviderRequest(server string, zoneId string, id string, body UpdateProviderJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpdateProviderRequestWithBody(server, zoneId, id, "application/json", bodyReader)
}

// NewUpdateProviderRequestWithBody generates requests for UpdateProvider with any type of body
func NewUpdateProviderRequestWithBody(server string, zoneId string, id string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "zoneId", runtime.ParamLocationPath, zoneId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/zones/%s/providers/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PATCH", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ListZonesWithResponse request
	ListZonesWithResponse(ctx context.Context, params *ListZonesParams, reqEditors ...RequestEditorFn) (*ListZonesResponse, error)

	// CreateZoneWithBodyWithResponse request with any body
	CreateZoneWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateZoneResponse, error)

	CreateZoneWithResponse(ctx context.Context, body CreateZoneJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateZoneResponse, error)

	// DeleteZoneWithResponse request
	DeleteZoneWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*DeleteZoneResponse, error)

	// GetZoneWithResponse request
	GetZoneWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetZoneResponse, error)

	// UpdateZoneWithBodyWithResponse request with any body
	UpdateZoneWithBodyWithResponse(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateZoneResponse, error)

	UpdateZoneWithResponse(ctx context.Context, id string, body UpdateZoneJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateZoneResponse, error)

	// ListProvidersWithResponse request
	ListProvidersWithResponse(ctx context.Context, zoneId string, params *ListProvidersParams, reqEditors ...RequestEditorFn) (*ListProvidersResponse, error)

	// CreateProviderWithBodyWithResponse request with any body
	CreateProviderWithBodyWithResponse(ctx context.Context, zoneId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateProviderResponse, error)

	CreateProviderWithResponse(ctx context.Context, zoneId string, body CreateProviderJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateProviderResponse, error)

	// DeleteProviderWithResponse request
	DeleteProviderWithResponse(ctx context.Context, zoneId string, id string, reqEditors ...RequestEditorFn) (*DeleteProviderResponse, error)

	// GetProviderWithResponse request
	GetProviderWithResponse(ctx context.Context, zoneId string, id string, reqEditors ...RequestEditorFn) (*GetProviderResponse, error)

	// UpdateProviderWithBodyWithResponse request with any body
	UpdateProviderWithBodyWithResponse(ctx context.Context, zoneId string, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateProviderResponse, error)

	UpdateProviderWithResponse(ctx context.Context, zoneId string, id string, body UpdateProviderJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateProviderResponse, error)
}

type ListZonesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Items []Zone `json:"items"`

		// PageInfo Pagination information
		PageInfo PageInfo `json:"page_info"`
	}
	JSONDefault *Error
}

// Status returns HTTPResponse.Status
func (r ListZonesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListZonesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateZoneResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Zone
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r CreateZoneResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateZoneResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteZoneResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r DeleteZoneResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteZoneResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetZoneResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Zone
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r GetZoneResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetZoneResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UpdateZoneResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Zone
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r UpdateZoneResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpdateZoneResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListProvidersResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Items []Provider `json:"items"`

		// PageInfo Pagination information
		PageInfo PageInfo `json:"page_info"`
	}
	JSONDefault *Error
}

// Status returns HTTPResponse.Status
func (r ListProvidersResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListProvidersResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateProviderResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Provider
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r CreateProviderResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateProviderResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteProviderResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r DeleteProviderResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteProviderResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetProviderResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Provider
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r GetProviderResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetProviderResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UpdateProviderResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Provider
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r UpdateProviderResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpdateProviderResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ListZonesWithResponse request returning *ListZonesResponse
func (c *ClientWithResponses) ListZonesWithResponse(ctx context.Context, params *ListZonesParams, reqEditors ...RequestEditorFn) (*ListZonesResponse, error) {
	rsp, err := c.ListZones(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListZonesResponse(rsp)
}

// CreateZoneWithBodyWithResponse request with arbitrary body returning *CreateZoneResponse
func (c *ClientWithResponses) CreateZoneWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateZoneResponse, error) {
	rsp, err := c.CreateZoneWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateZoneResponse(rsp)
}

func (c *ClientWithResponses) CreateZoneWithResponse(ctx context.Context, body CreateZoneJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateZoneResponse, error) {
	rsp, err := c.CreateZone(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateZoneResponse(rsp)
}

// DeleteZoneWithResponse request returning *DeleteZoneResponse
func (c *ClientWithResponses) DeleteZoneWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*DeleteZoneResponse, error) {
	rsp, err := c.DeleteZone(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteZoneResponse(rsp)
}

// GetZoneWithResponse request returning *GetZoneResponse
func (c *ClientWithResponses) GetZoneWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetZoneResponse, error) {
	rsp, err := c.GetZone(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetZoneResponse(rsp)
}

// UpdateZoneWithBodyWithResponse request with arbitrary body returning *UpdateZoneResponse
func (c *ClientWithResponses) UpdateZoneWithBodyWithResponse(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateZoneResponse, error) {
	rsp, err := c.UpdateZoneWithBody(ctx, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateZoneResponse(rsp)
}

func (c *ClientWithResponses) UpdateZoneWithResponse(ctx context.Context, id string, body UpdateZoneJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateZoneResponse, error) {
	rsp, err := c.UpdateZone(ctx, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateZoneResponse(rsp)
}

// ListProvidersWithResponse request returning *ListProvidersResponse
func (c *ClientWithResponses) ListProvidersWithResponse(ctx context.Context, zoneId string, params *ListProvidersParams, reqEditors ...RequestEditorFn) (*ListProvidersResponse, error) {
	rsp, err := c.ListProviders(ctx, zoneId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListProvidersResponse(rsp)
}

// CreateProviderWithBodyWithResponse request with arbitrary body returning *CreateProviderResponse
func (c *ClientWithResponses) CreateProviderWithBodyWithResponse(ctx context.Context, zoneId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateProviderResponse, error) {
	rsp, err := c.CreateProviderWithBody(ctx, zoneId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateProviderResponse(rsp)
}

func (c *ClientWithResponses) CreateProviderWithResponse(ctx context.Context, zoneId string, body CreateProviderJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateProviderResponse, error) {
	rsp, err := c.CreateProvider(ctx, zoneId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateProviderResponse(rsp)
}

// DeleteProviderWithResponse request returning *DeleteProviderResponse
func (c *ClientWithResponses) DeleteProviderWithResponse(ctx context.Context, zoneId string, id string, reqEditors ...RequestEditorFn) (*DeleteProviderResponse, error) {
	rsp, err := c.DeleteProvider(ctx, zoneId, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteProviderResponse(rsp)
}

// GetProviderWithResponse request returning *GetProviderResponse
func (c *ClientWithResponses) GetProviderWithResponse(ctx context.Context, zoneId string, id string, reqEditors ...RequestEditorFn) (*GetProviderResponse, error) {
	rsp, err := c.GetProvider(ctx, zoneId, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetProviderResponse(rsp)
}

// UpdateProviderWithBodyWithResponse request with arbitrary body returning *UpdateProviderResponse
func (c *ClientWithResponses) UpdateProviderWithBodyWithResponse(ctx context.Context, zoneId string, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateProviderResponse, error) {
	rsp, err := c.UpdateProviderWithBody(ctx, zoneId, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateProviderResponse(rsp)
}

func (c *ClientWithResponses) UpdateProviderWithResponse(ctx context.Context, zoneId string, id string, body UpdateProviderJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateProviderResponse, error) {
	rsp, err := c.UpdateProvider(ctx, zoneId, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateProviderResponse(rsp)
}

// ParseListZonesResponse parses an HTTP response from a ListZonesWithResponse call
func ParseListZonesResponse(rsp *http.Response) (*ListZonesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListZonesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Items []Zone `json:"items"`

			// PageInfo Pagination information
			PageInfo PageInfo `json:"page_info"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseCreateZoneResponse parses an HTTP response from a CreateZoneWithResponse call
func ParseCreateZoneResponse(rsp *http.Response) (*CreateZoneResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateZoneResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Zone
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseDeleteZoneResponse parses an HTTP response from a DeleteZoneWithResponse call
func ParseDeleteZoneResponse(rsp *http.Response) (*DeleteZoneResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteZoneResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseGetZoneResponse parses an HTTP response from a GetZoneWithResponse call
func ParseGetZoneResponse(rsp *http.Response) (*GetZoneResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetZoneResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Zone
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseUpdateZoneResponse parses an HTTP response from a UpdateZoneWithResponse call
func ParseUpdateZoneResponse(rsp *http.Response) (*UpdateZoneResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpdateZoneResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Zone
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseListProvidersResponse parses an HTTP response from a ListProvidersWithResponse call
func ParseListProvidersResponse(rsp *http.Response) (*ListProvidersResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListProvidersResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Items []Provider `json:"items"`

			// PageInfo Pagination information
			PageInfo PageInfo `json:"page_info"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseCreateProviderResponse parses an HTTP response from a CreateProviderWithResponse call
func ParseCreateProviderResponse(rsp *http.Response) (*CreateProviderResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateProviderResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Provider
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseDeleteProviderResponse parses an HTTP response from a DeleteProviderWithResponse call
func ParseDeleteProviderResponse(rsp *http.Response) (*DeleteProviderResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteProviderResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseGetProviderResponse parses an HTTP response from a GetProviderWithResponse call
func ParseGetProviderResponse(rsp *http.Response) (*GetProviderResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetProviderResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Provider
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseUpdateProviderResponse parses an HTTP response from a UpdateProviderWithResponse call
func ParseUpdateProviderResponse(rsp *http.Response) (*UpdateProviderResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpdateProviderResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Provider
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xbaW8bOdL+KwTfAV57V1c8M4tdfVl47Oysc0wMJ0GABF6B6i61GHeTHZJtRQn03xck",
	"+2621Dpsx7P+pKPJKrJY9TxVJeo79ngUcwZMSTz+jqU3h4iYt8+F4EK/8UF6gsaKcobH9mskQMacScA9",
	"HAseg1AUzCyP+6Bf1TIGPMZSCcoCvOrhCKQkgfuZVEQlsvSIJdEUBF6teljAl4QK8PH4Uy6jZ9XkE697",
	"WFEVQrY83MsE8eln8JTWcUkCuGAzrrUQ36d6OyS8LC1+RkIJvdp2L0lAGdEfEGUzLiLzvrFtYP7ES4R0",
	"WezMfI9iTpmiLECKIzUHFBKpEFUQIcrMF14iBDCFYrtFloQhmepNKZFAr2m1OZETBl/VJE7tWlX7YQ5q",
	"DkKLFoCIABRxAUajRGSm7KO61lTLlPMQCMvUxAJuKU9kZ1VWyxRmWmUnNVIRoba14YyKvYxY86+qRV1b",
	"L3madihkPMrlbYLfUh8cOzlF2TNEJSJILqVevpoThWQSxyEFiYjngZR6l1cgeSI8/R3zEQlDvtCPFRcS",
	"Hb2XICTiAp3qeZ5xTXmsp5FEzYEp/R0MmkEaUmBqQv3m8t6cJmqOTgYjZAch6ms5Mwqii0+mkiV4AvSL",
	"amq4YL5ZlkSL1G1IpstO03bxOJvRINHn4nIWTwBR4E+IQ/5zpqhaIjNEh62iEUhFohj3sA1gPMY+UdDX",
	"T7BjExV5dfH/TiLC+gKIrw2Byg97OCJfXwEL1ByPT0a//L2DwVxn8J7RLwmULI/4zDh3nHmVU1B+Tk2B",
	"EgSSMXj6uV8S3EOJ1bWgap5G0DfOwLWViLLsi2cO/YxEsNFaZlBV9q+/bhTNRUAY/WaO0+20pQE2kviC",
	"SaTmVK61WSy44h4PZVPkZfqon5rNy10yI4D60VZDjOsIPFkXX0P0JgZ2cY7OOGPgKZStZktNWhEXmXmA",
	"+QYk9ZPc2xNBOwUv92HizUkYAgtgEoGac19ONCpxocAY3gC7k8RbxBMhyFI//7y4kRO9kh1WJiCgUon9",
	"tyg9HsPBtqT4Dey3nkSC0HnFHkJWDfpZOQhJhkngAIarV31JZrA1JPzt53rUxkQpEFrofz6R/rdR/x/X",
	"fz3657iffzj+y0+uGLRf6AwqiTQHw1cthoS4h29g6RHh929JEqrSZ58K0Ay4NHTcMGnsb+IGO2QHZtCG",
	"cCLQR86gijdoCiFngSZxvCnvoJrl6ihXaEtPL8XYCtRXqLCy93Km0oDAZqJyZsQ0N/bWFARoxkXKqCxA",
	"BDFYlIH1QNnF+myig7Q0fzha0DBEU0DAPLGMFfgmeZKKC/D1oERAuDx+eOr/0zL2XsR6d0S6I3EemCi3",
	"IMadiXBP4tua6HYith2IrAacTUB0wB5KsW0N+r03uLkW/Qy0GvRjCL5Sad4fGAMH6C0oXb5p7NCvAiJ+",
	"awq47Sqvg2PlPit7wtQHxtSWw0MkDHOslIMDlDRu4F2n3sw9SccPnmqdP2+t4ypKeAzMCZFd+HytW1kB",
	"Xd3qnqqwlYObUuZxGEeXFK72oUYmw0hpwaB5SORdwhTCCEPleqLJT26gOkuk4hHyeUQoMziFjs7+OH39",
	"/NhoLAFjbp05l6oF0JpB97/ZtktNdq8tM4PVE98TE2Bajt/etT9fMhJRD53ZxOCqhD+ISpTNd/VhUzXx",
	"jQeTIi9rU3T58uy5lpiNND5VgXSkYRnNQr6Qbn37dALbjqFCrG2U15WH2qixus18Rm9jIl1VJUHcgtB0",
	"RXyiyDqNpxWNb81E9DqdmK8AHQ0WEIb9G8YXbGj226+o7FuVxx2WSqVMXIlXsSY7olr1b5Ja5tKq3Bdv",
	"3/yBPsAUvYSlIYMtzCrAdpHckosVZ+PQ+6uLFAMLV9q5WmvTti4Ut9hck6vbFJqR3UXX+1b2wDc5aa8t",
	"XhorrZ1LmwVLTnG9Nq2oRm1WrU2qfYFN6UdRR5antUWQ0d2vaOgSO84UZO2ydDlzwWZ859NrMYdrLdeb",
	"CvEUKHPbXz+mFvRddoy1LSd2a2o5yU3u4q7cz/LMNclIUktBIQ8o27WXXO0gO3nbmTWU6bFTs/ljhWWr",
	"6ez2Teb02H+E5PU+08sHyAxn5keWdEH3mCh20Ltv3uhqGtY8dk2PUD/etT9oarWjmAhFSZiCyPGB/Rkd",
	"SVcdfNzRz3+o9t1TRbRtRbQjvyheUEyNYRr+lDAJ6rhbC6QcUm2tDZ0KgJcIqpYmfmwQTIEIEDoxLT79",
	"K/PfFx/e4To6vPjwDv1mhqF3Jos9Le48Wf8zlxmNvcywYiVzpWK80guh6Y3AquiX9odmdHppc/6IMBJk",
	"8WxvYqk5UFH0XQa42HxpNu7hWxDSSh0NRoNnWX5KYorH+OfBaDDCJnOZGysMjQb9LnB18a9AJYJJRFBI",
	"pUJ8lq4ow4PytS+/3gHSkGPeX/h4jF9RqT4aZVq9IBEoEBKPP33HVKv6koBYZhnDOMsf7P1QRwNx1XPP",
	"Sy/07TAzpBFVlYk5WTwbjUz80yiJzKeRCf/0Y37MlCkIzDXSa80A9saqMe7JaGQvqzIFNtUmxQ264Wdp",
	"oa7QXMXrvImav/lJwAyP8f8Ni9u0w/Qq7dAkRI7f1GISwCTzv3UC8purjVTPqC9LcuTpdQTH59aK6Cq7",
	"wmtGpJbdwibrlmxv4TqU124Pl7HAuF4ZBT5d63OTSRQRsUw91vq7DjYSaGfF1oWvtT25dESM5XVZSic7",
	"BMsApW1WqoMdUclDMwbYLRWcRZoUtJSL09dVCKiGmNWdJsT64ECq37i/PJiZSzn1amW9Yw8n3+zEzfPc",
	"sR39WFzOGjfvHNZ8btVL8Xr4nfor63shuPLESxAR0esNl8iO0R5pTJde60VUSUSk5B41rpabsOFV52Z+",
	"6lU15HZcSro4xz2Lr5pkCng1VWGBJpbR20G6iaC/NLf5aKHF2rTtnHvrydgHRWgoNRsTlP8Caw53urT2",
	"r57g76Ae/viesGFPn/kdVLvDxER5c0ezy6TEWez/v6z+oumqFKueY+c/iPPcDXulNcITe92Fh1rjdmAv",
	"/XLhr4ZZ+bhNAZLPyf6BU9ywSRU3647LXM+d1h6Vn5m2nm2GlecRtnwzM4ts3FV23EMuRlWvMXcauu6G",
	"8/UPXmtlKqqQY13sXjlrn6ItvzL9VLgdqHCLSzGfQVGBA10LuLyH1d/vr3O1v8i1lG6li/MumDqMhx+e",
	"WGt3+u+YXItQcRHs/f/Z8ZHVluX/pznCYh1L71h2ljS6Ksu7dno3PzyVo81ydINr7FSW5vHYWpo+0vN/",
	"ArQfoSDe6LIbC+NseKM41hYsXSlyFcaPx3XvjvTvp6J+ipG9SvJNpG9EitvMexMR4jEe6trvvwEAAP//",
	"Mx7go7FFAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
