// Package client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package client

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/nullable"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for ProviderType.
const (
	ProviderTypeExternal         ProviderType = "external"
	ProviderTypeKeycardDirectory ProviderType = "keycard-directory"
	ProviderTypeKeycardVault     ProviderType = "keycard-vault"
)

// Defines values for ListProvidersParamsType0.
const (
	ListProvidersParamsType0External ListProvidersParamsType0 = "external"
)

// Defines values for ListProvidersParamsType1.
const (
	KeycardVault ListProvidersParamsType1 = "keycard-vault"
)

// Defines values for ListProvidersParamsType2.
const (
	KeycardDirectory ListProvidersParamsType2 = "keycard-directory"
)

// Application An Application is a software system with an associated identity that can access Resources. It may act on its own behalf (machine-to-machine) or on behalf of a user (delegated access).
type Application struct {
	// CreatedAt Entity creation timestamp
	CreatedAt time.Time `json:"created_at"`

	// DependenciesCount Number of resource dependencies
	DependenciesCount int `json:"dependencies_count"`

	// Description Human-readable description
	Description nullable.Nullable[string] `json:"description,omitempty"`

	// Id Unique identifier of the application
	Id string `json:"id"`

	// Identifier User specified identifier, unique within the zone
	Identifier string `json:"identifier"`

	// Metadata Entity metadata
	Metadata *Metadata `json:"metadata,omitempty"`

	// Name Human-readable name
	Name string `json:"name"`

	// OrganizationId Organization that owns this application
	OrganizationId string `json:"organization_id"`

	// Protocols Protocol-specific configuration
	Protocols nullable.Nullable[struct {
		// Oauth2 OAuth 2.0 protocol configuration
		Oauth2 nullable.Nullable[ApplicationOAuth2Protocol] `json:"oauth2,omitempty"`
	}] `json:"protocols,omitempty"`

	// Slug URL-safe identifier, unique within the zone
	Slug string `json:"slug"`

	// UpdatedAt Entity update timestamp
	UpdatedAt time.Time `json:"updated_at"`

	// ZoneId Zone this application belongs to
	ZoneId string `json:"zone_id"`
}

// ApplicationCreate Schema for creating a new application
type ApplicationCreate struct {
	// Dependencies Dependencies of the application
	Dependencies *[]struct {
		// Id Resource identifier
		Id   string  `json:"id"`
		Type *string `json:"type,omitempty"`
	} `json:"dependencies,omitempty"`

	// Description Human-readable description
	Description nullable.Nullable[string] `json:"description,omitempty"`

	// Identifier User specified identifier, unique within the zone
	Identifier string `json:"identifier"`

	// Metadata Entity metadata
	Metadata *Metadata `json:"metadata,omitempty"`

	// Name Human-readable name
	Name string `json:"name"`

	// Protocols Protocol-specific configuration for application creation
	Protocols *ApplicationProtocolCreate `json:"protocols,omitempty"`
}

// ApplicationOAuth2Protocol OAuth 2.0 protocol configuration
type ApplicationOAuth2Protocol struct {
	// RedirectUris OAuth 2.0 redirect URIs for this application
	RedirectUris nullable.Nullable[[]string] `json:"redirect_uris,omitempty"`
}

// ApplicationOAuth2ProtocolCreate OAuth 2.0 protocol configuration for application creation
type ApplicationOAuth2ProtocolCreate struct {
	// RedirectUris OAuth 2.0 redirect URIs for this application
	RedirectUris *[]string `json:"redirect_uris,omitempty"`
}

// ApplicationOAuth2ProtocolUpdate OAuth 2.0 protocol configuration for application update
type ApplicationOAuth2ProtocolUpdate struct {
	// RedirectUris OAuth 2.0 redirect URIs for this application (set to null or [] to unset)
	RedirectUris nullable.Nullable[[]string] `json:"redirect_uris,omitempty"`
}

// ApplicationProtocolCreate Protocol-specific configuration for application creation
type ApplicationProtocolCreate struct {
	// Oauth2 OAuth 2.0 protocol configuration for application creation
	Oauth2 *ApplicationOAuth2ProtocolCreate `json:"oauth2,omitempty"`
}

// ApplicationProtocolUpdate Protocol-specific configuration for application update
type ApplicationProtocolUpdate struct {
	// Oauth2 OAuth 2.0 protocol configuration for application update
	Oauth2 nullable.Nullable[ApplicationOAuth2ProtocolUpdate] `json:"oauth2,omitempty"`
}

// ApplicationUpdate Schema for updating an existing application
type ApplicationUpdate struct {
	// Description Human-readable description
	Description nullable.Nullable[string] `json:"description,omitempty"`

	// Identifier User specified identifier, unique within the zone
	Identifier *string `json:"identifier,omitempty"`

	// Metadata Entity metadata (set to null or {} to remove metadata)
	Metadata nullable.Nullable[MetadataUpdate] `json:"metadata,omitempty"`

	// Name Human-readable name
	Name *string `json:"name,omitempty"`

	// Protocols Protocol-specific configuration for application update
	Protocols nullable.Nullable[ApplicationProtocolUpdate] `json:"protocols,omitempty"`
}

// Error Error response
type Error struct {
	Code    string  `json:"code"`
	Message string  `json:"message"`
	Status  float32 `json:"status"`
}

// Metadata Entity metadata
type Metadata struct {
	// DocsUrl Documentation URL
	DocsUrl *string `json:"docs_url,omitempty"`
}

// MetadataUpdate Entity metadata (set to null or {} to remove metadata)
type MetadataUpdate struct {
	// DocsUrl Documentation URL (set to null to unset)
	DocsUrl nullable.Nullable[string] `json:"docs_url,omitempty"`
}

// PageInfo Pagination information
type PageInfo struct {
	// EndCursor Cursor pointing to the last item in the current page
	EndCursor nullable.Nullable[string] `json:"end_cursor,omitempty"`

	// HasNextPage Whether there are more items after the current page
	HasNextPage bool `json:"has_next_page"`

	// HasPreviousPage Whether there are items before the current page
	HasPreviousPage bool `json:"has_previous_page"`

	// StartCursor Cursor pointing to the first item in the current page
	StartCursor nullable.Nullable[string] `json:"start_cursor,omitempty"`
}

// Provider A Provider is a system that supplies access to Resources and allows actors (Users or Applications) to authenticate.
type Provider struct {
	// ClientId OAuth 2.0 client identifier
	ClientId nullable.Nullable[string] `json:"client_id,omitempty"`

	// ClientSecretSet Indicates whether a client secret is configured
	ClientSecretSet *bool `json:"client_secret_set,omitempty"`

	// CreatedAt Entity creation timestamp
	CreatedAt time.Time `json:"created_at"`

	// Description Human-readable description
	Description nullable.Nullable[string] `json:"description,omitempty"`

	// Id Unique identifier of the provider
	Id string `json:"id"`

	// Identifier User specified identifier, unique within the zone
	Identifier string `json:"identifier"`

	// Name Human-readable name
	Name string `json:"name"`

	// OrganizationId Organization that owns this provider
	OrganizationId string `json:"organization_id"`

	// Protocols Protocol-specific configuration
	Protocols nullable.Nullable[struct {
		// Oauth2 OAuth 2.0 protocol configuration
		Oauth2 nullable.Nullable[ProviderOAuth2Protocol] `json:"oauth2,omitempty"`

		// Openid OpenID Connect protocol configuration
		Openid nullable.Nullable[ProviderOpenIDProtocol] `json:"openid,omitempty"`
	}] `json:"protocols,omitempty"`

	// Slug URL-safe identifier, unique within the zone
	Slug string        `json:"slug"`
	Type *ProviderType `json:"type,omitempty"`

	// UpdatedAt Entity update timestamp
	UpdatedAt time.Time `json:"updated_at"`

	// ZoneId Zone this provider belongs to
	ZoneId string `json:"zone_id"`
}

// ProviderType defines model for Provider.Type.
type ProviderType string

// ProviderCreate Schema for creating a new provider
type ProviderCreate struct {
	// ClientId OAuth 2.0 client identifier
	ClientId *string `json:"client_id,omitempty"`

	// ClientSecret OAuth 2.0 client secret (will be encrypted and stored securely)
	ClientSecret *string `json:"client_secret,omitempty"`

	// Description Human-readable description
	Description nullable.Nullable[string] `json:"description,omitempty"`

	// Identifier User specified identifier, unique within the zone
	Identifier string `json:"identifier"`

	// Name Human-readable name
	Name string `json:"name"`

	// Protocols Protocol-specific configuration for provider creation
	Protocols *ProviderProtocolCreate `json:"protocols,omitempty"`
}

// ProviderOAuth2Protocol OAuth 2.0 protocol configuration
type ProviderOAuth2Protocol struct {
	AuthorizationEndpoint         nullable.Nullable[string]   `json:"authorization_endpoint,omitempty"`
	CodeChallengeMethodsSupported nullable.Nullable[[]string] `json:"code_challenge_methods_supported,omitempty"`
	JwksUri                       nullable.Nullable[string]   `json:"jwks_uri,omitempty"`
	RegistrationEndpoint          nullable.Nullable[string]   `json:"registration_endpoint,omitempty"`
	ScopesSupported               nullable.Nullable[[]string] `json:"scopes_supported,omitempty"`
	TokenEndpoint                 nullable.Nullable[string]   `json:"token_endpoint,omitempty"`
}

// ProviderOAuth2ProtocolCreate OAuth 2.0 protocol configuration for provider creation
type ProviderOAuth2ProtocolCreate struct {
	AuthorizationEndpoint         *string   `json:"authorization_endpoint,omitempty"`
	CodeChallengeMethodsSupported *[]string `json:"code_challenge_methods_supported,omitempty"`
	JwksUri                       *string   `json:"jwks_uri,omitempty"`
	RegistrationEndpoint          *string   `json:"registration_endpoint,omitempty"`
	ScopesSupported               *[]string `json:"scopes_supported,omitempty"`
	TokenEndpoint                 *string   `json:"token_endpoint,omitempty"`
}

// ProviderOAuth2ProtocolUpdate OAuth 2.0 protocol configuration. Set to null to remove all OAuth2 config.
type ProviderOAuth2ProtocolUpdate struct {
	AuthorizationEndpoint         nullable.Nullable[string]   `json:"authorization_endpoint,omitempty"`
	CodeChallengeMethodsSupported nullable.Nullable[[]string] `json:"code_challenge_methods_supported,omitempty"`
	JwksUri                       nullable.Nullable[string]   `json:"jwks_uri,omitempty"`
	RegistrationEndpoint          nullable.Nullable[string]   `json:"registration_endpoint,omitempty"`
	ScopesSupported               nullable.Nullable[[]string] `json:"scopes_supported,omitempty"`
	TokenEndpoint                 nullable.Nullable[string]   `json:"token_endpoint,omitempty"`
}

// ProviderOpenIDProtocol OpenID Connect protocol configuration
type ProviderOpenIDProtocol struct {
	UserinfoEndpoint nullable.Nullable[string] `json:"userinfo_endpoint,omitempty"`
}

// ProviderOpenIDProtocolCreate OpenID Connect protocol configuration for provider creation
type ProviderOpenIDProtocolCreate struct {
	UserinfoEndpoint *string `json:"userinfo_endpoint,omitempty"`
}

// ProviderOpenIDProtocolUpdate OpenID Connect protocol configuration. Set to null to remove all OpenID config.
type ProviderOpenIDProtocolUpdate struct {
	UserinfoEndpoint nullable.Nullable[string] `json:"userinfo_endpoint,omitempty"`
}

// ProviderProtocolCreate Protocol-specific configuration for provider creation
type ProviderProtocolCreate struct {
	// Oauth2 OAuth 2.0 protocol configuration for provider creation
	Oauth2 *ProviderOAuth2ProtocolCreate `json:"oauth2,omitempty"`

	// Openid OpenID Connect protocol configuration for provider creation
	Openid *ProviderOpenIDProtocolCreate `json:"openid,omitempty"`
}

// ProviderProtocolUpdate Protocol-specific configuration. Set to null to remove all protocols.
type ProviderProtocolUpdate struct {
	// Oauth2 OAuth 2.0 protocol configuration. Set to null to remove all OAuth2 config.
	Oauth2 nullable.Nullable[ProviderOAuth2ProtocolUpdate] `json:"oauth2,omitempty"`

	// Openid OpenID Connect protocol configuration. Set to null to remove all OpenID config.
	Openid nullable.Nullable[ProviderOpenIDProtocolUpdate] `json:"openid,omitempty"`
}

// ProviderUpdate Schema for updating an existing provider
type ProviderUpdate struct {
	// ClientId OAuth 2.0 client identifier. Set to null to remove.
	ClientId nullable.Nullable[string] `json:"client_id,omitempty"`

	// ClientSecret OAuth 2.0 client secret (will be encrypted and stored securely). Set to null to remove.
	ClientSecret nullable.Nullable[string] `json:"client_secret,omitempty"`

	// Description Human-readable description
	Description nullable.Nullable[string] `json:"description,omitempty"`

	// Identifier User specified identifier, unique within the zone
	Identifier *string `json:"identifier,omitempty"`

	// Name Human-readable name
	Name *string `json:"name,omitempty"`

	// Protocols Protocol-specific configuration. Set to null to remove all protocols.
	Protocols nullable.Nullable[ProviderProtocolUpdate] `json:"protocols,omitempty"`
}

// Zone A zone for organizing resources within an organization
type Zone struct {
	// Cname Custom domain name (CNAME) for the zone
	Cname *string `json:"cname,omitempty"`

	// CreatedAt Entity creation timestamp
	CreatedAt time.Time `json:"created_at"`

	// Description Human-readable description
	Description nullable.Nullable[string] `json:"description,omitempty"`

	// Id Unique identifier of the zone
	Id string `json:"id"`

	// Name Human-readable name
	Name string `json:"name"`

	// OrganizationId Organization that owns this zone
	OrganizationId string `json:"organization_id"`

	// Protocols Protocol configuration for a zone
	Protocols struct {
		// Oauth2 OAuth 2.0 protocol configuration for a zone
		Oauth2 ZoneOAuth2Protocol `json:"oauth2"`

		// Openid OpenID Connect protocol configuration for a zone
		Openid ZoneOpenIDProtocol `json:"openid"`
	} `json:"protocols"`

	// Slug URL-safe identifier, unique within the zone
	Slug string `json:"slug"`

	// UpdatedAt Entity update timestamp
	UpdatedAt time.Time `json:"updated_at"`

	// UserIdentityProviderId Provider ID configured for user login
	UserIdentityProviderId *string `json:"user_identity_provider_id,omitempty"`
}

// ZoneCreate Schema for creating a new zone
type ZoneCreate struct {
	// Cname Custom domain name (CNAME) for the zone
	Cname *string `json:"cname,omitempty"`

	// Description Human-readable description
	Description nullable.Nullable[string] `json:"description,omitempty"`

	// Name Human-readable name
	Name string `json:"name"`

	// Protocols Protocol configuration for zone creation
	Protocols *ZoneProtocolCreate `json:"protocols,omitempty"`
}

// ZoneOAuth2Protocol OAuth 2.0 protocol configuration for a zone
type ZoneOAuth2Protocol struct {
	// AuthorizationEndpoint OAuth 2.0 authorization endpoint
	AuthorizationEndpoint string `json:"authorization_endpoint"`

	// AuthorizationServerMetadata OAuth 2.0 Authorization Server Metadata endpoint (.well-known/oauth-authorization-server)
	AuthorizationServerMetadata string `json:"authorization_server_metadata"`

	// DcrEnabled Whether Dynamic Client Registration is enabled
	DcrEnabled bool `json:"dcr_enabled"`

	// Issuer OAuth 2.0 issuer identifier
	Issuer string `json:"issuer"`

	// JwksUri JSON Web Key Set endpoint
	JwksUri string `json:"jwks_uri"`

	// PkceRequired Whether PKCE is required for authorization code flows
	PkceRequired bool `json:"pkce_required"`

	// RedirectUri OAuth 2.0 redirect URI for this zone
	RedirectUri string `json:"redirect_uri"`

	// RegistrationEndpoint OAuth 2.0 Dynamic Client Registration endpoint
	RegistrationEndpoint string `json:"registration_endpoint"`

	// TokenEndpoint OAuth 2.0 token endpoint
	TokenEndpoint string `json:"token_endpoint"`
}

// ZoneOAuth2ProtocolCreate OAuth 2.0 protocol configuration for zone creation
type ZoneOAuth2ProtocolCreate struct {
	// DcrEnabled Whether Dynamic Client Registration is enabled
	DcrEnabled *bool `json:"dcr_enabled,omitempty"`

	// PkceRequired Whether PKCE is required for authorization code flows
	PkceRequired *bool `json:"pkce_required,omitempty"`
}

// ZoneOAuth2ProtocolUpdate OAuth 2.0 protocol configuration update for a zone (partial update)
type ZoneOAuth2ProtocolUpdate struct {
	// DcrEnabled Whether Dynamic Client Registration is enabled
	DcrEnabled nullable.Nullable[bool] `json:"dcr_enabled,omitempty"`

	// PkceRequired Whether PKCE is required for authorization code flows
	PkceRequired nullable.Nullable[bool] `json:"pkce_required,omitempty"`
}

// ZoneOpenIDProtocol OpenID Connect protocol configuration for a zone
type ZoneOpenIDProtocol struct {
	// ProviderConfiguration OpenID Connect Provider Configuration endpoint (.well-known/openid-configuration)
	ProviderConfiguration string `json:"provider_configuration"`

	// UserinfoEndpoint OpenID Connect UserInfo endpoint
	UserinfoEndpoint string `json:"userinfo_endpoint"`
}

// ZoneProtocolCreate Protocol configuration for zone creation
type ZoneProtocolCreate struct {
	// Oauth2 OAuth 2.0 protocol configuration for zone creation
	Oauth2 *ZoneOAuth2ProtocolCreate `json:"oauth2,omitempty"`
}

// ZoneProtocolUpdate Protocol configuration update for a zone (partial update)
type ZoneProtocolUpdate struct {
	// Oauth2 OAuth 2.0 protocol configuration update for a zone (partial update)
	Oauth2 *ZoneOAuth2ProtocolUpdate `json:"oauth2,omitempty"`
}

// ZoneUpdate Schema for updating an existing zone (partial update)
type ZoneUpdate struct {
	// Cname Custom domain name (CNAME) for the zone (set to null to remove)
	Cname nullable.Nullable[string] `json:"cname,omitempty"`

	// Description Human-readable description
	Description nullable.Nullable[string] `json:"description,omitempty"`

	// Name Human-readable name
	Name *string `json:"name,omitempty"`

	// Protocols Protocol configuration update for a zone (partial update)
	Protocols nullable.Nullable[ZoneProtocolUpdate] `json:"protocols,omitempty"`

	// UserIdentityProviderId Provider ID to configure for user login (set to null to unset)
	UserIdentityProviderId nullable.Nullable[string] `json:"user_identity_provider_id,omitempty"`
}

// ListZonesParams defines parameters for ListZones.
type ListZonesParams struct {
	Slug   *string `form:"slug,omitempty" json:"slug,omitempty"`
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListApplicationsParams defines parameters for ListApplications.
type ListApplicationsParams struct {
	Slug       *string `form:"slug,omitempty" json:"slug,omitempty"`
	Identifier *string `form:"identifier,omitempty" json:"identifier,omitempty"`
	Cursor     *string `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit      *int    `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListProvidersParams defines parameters for ListProviders.
type ListProvidersParams struct {
	Slug       *string `form:"slug,omitempty" json:"slug,omitempty"`
	Identifier *string `form:"identifier,omitempty" json:"identifier,omitempty"`
	Type       *struct {
		union json.RawMessage
	} `form:"type,omitempty" json:"type,omitempty"`
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListProvidersParamsType0 defines parameters for ListProviders.
type ListProvidersParamsType0 string

// ListProvidersParamsType1 defines parameters for ListProviders.
type ListProvidersParamsType1 string

// ListProvidersParamsType2 defines parameters for ListProviders.
type ListProvidersParamsType2 string

// CreateZoneJSONRequestBody defines body for CreateZone for application/json ContentType.
type CreateZoneJSONRequestBody = ZoneCreate

// UpdateZoneJSONRequestBody defines body for UpdateZone for application/json ContentType.
type UpdateZoneJSONRequestBody = ZoneUpdate

// CreateApplicationJSONRequestBody defines body for CreateApplication for application/json ContentType.
type CreateApplicationJSONRequestBody = ApplicationCreate

// UpdateApplicationJSONRequestBody defines body for UpdateApplication for application/json ContentType.
type UpdateApplicationJSONRequestBody = ApplicationUpdate

// CreateProviderJSONRequestBody defines body for CreateProvider for application/json ContentType.
type CreateProviderJSONRequestBody = ProviderCreate

// UpdateProviderJSONRequestBody defines body for UpdateProvider for application/json ContentType.
type UpdateProviderJSONRequestBody = ProviderUpdate

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ListZones request
	ListZones(ctx context.Context, params *ListZonesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateZoneWithBody request with any body
	CreateZoneWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateZone(ctx context.Context, body CreateZoneJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteZone request
	DeleteZone(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetZone request
	GetZone(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateZoneWithBody request with any body
	UpdateZoneWithBody(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	UpdateZone(ctx context.Context, id string, body UpdateZoneJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListApplications request
	ListApplications(ctx context.Context, zoneId string, params *ListApplicationsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateApplicationWithBody request with any body
	CreateApplicationWithBody(ctx context.Context, zoneId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateApplication(ctx context.Context, zoneId string, body CreateApplicationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteApplication request
	DeleteApplication(ctx context.Context, zoneId string, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApplication request
	GetApplication(ctx context.Context, zoneId string, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateApplicationWithBody request with any body
	UpdateApplicationWithBody(ctx context.Context, zoneId string, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	UpdateApplication(ctx context.Context, zoneId string, id string, body UpdateApplicationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListProviders request
	ListProviders(ctx context.Context, zoneId string, params *ListProvidersParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateProviderWithBody request with any body
	CreateProviderWithBody(ctx context.Context, zoneId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateProvider(ctx context.Context, zoneId string, body CreateProviderJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteProvider request
	DeleteProvider(ctx context.Context, zoneId string, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetProvider request
	GetProvider(ctx context.Context, zoneId string, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateProviderWithBody request with any body
	UpdateProviderWithBody(ctx context.Context, zoneId string, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	UpdateProvider(ctx context.Context, zoneId string, id string, body UpdateProviderJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ListZones(ctx context.Context, params *ListZonesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListZonesRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateZoneWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateZoneRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateZone(ctx context.Context, body CreateZoneJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateZoneRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteZone(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteZoneRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetZone(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetZoneRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateZoneWithBody(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateZoneRequestWithBody(c.Server, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateZone(ctx context.Context, id string, body UpdateZoneJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateZoneRequest(c.Server, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListApplications(ctx context.Context, zoneId string, params *ListApplicationsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListApplicationsRequest(c.Server, zoneId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateApplicationWithBody(ctx context.Context, zoneId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateApplicationRequestWithBody(c.Server, zoneId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateApplication(ctx context.Context, zoneId string, body CreateApplicationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateApplicationRequest(c.Server, zoneId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteApplication(ctx context.Context, zoneId string, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteApplicationRequest(c.Server, zoneId, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApplication(ctx context.Context, zoneId string, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApplicationRequest(c.Server, zoneId, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateApplicationWithBody(ctx context.Context, zoneId string, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateApplicationRequestWithBody(c.Server, zoneId, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateApplication(ctx context.Context, zoneId string, id string, body UpdateApplicationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateApplicationRequest(c.Server, zoneId, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListProviders(ctx context.Context, zoneId string, params *ListProvidersParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListProvidersRequest(c.Server, zoneId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateProviderWithBody(ctx context.Context, zoneId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateProviderRequestWithBody(c.Server, zoneId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateProvider(ctx context.Context, zoneId string, body CreateProviderJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateProviderRequest(c.Server, zoneId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteProvider(ctx context.Context, zoneId string, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteProviderRequest(c.Server, zoneId, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetProvider(ctx context.Context, zoneId string, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetProviderRequest(c.Server, zoneId, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateProviderWithBody(ctx context.Context, zoneId string, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateProviderRequestWithBody(c.Server, zoneId, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateProvider(ctx context.Context, zoneId string, id string, body UpdateProviderJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateProviderRequest(c.Server, zoneId, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListZonesRequest generates requests for ListZones
func NewListZonesRequest(server string, params *ListZonesParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/zones")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Slug != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "slug", runtime.ParamLocationQuery, *params.Slug); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Cursor != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "cursor", runtime.ParamLocationQuery, *params.Cursor); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateZoneRequest calls the generic CreateZone builder with application/json body
func NewCreateZoneRequest(server string, body CreateZoneJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateZoneRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateZoneRequestWithBody generates requests for CreateZone with any type of body
func NewCreateZoneRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/zones")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteZoneRequest generates requests for DeleteZone
func NewDeleteZoneRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/zones/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetZoneRequest generates requests for GetZone
func NewGetZoneRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/zones/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUpdateZoneRequest calls the generic UpdateZone builder with application/json body
func NewUpdateZoneRequest(server string, id string, body UpdateZoneJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpdateZoneRequestWithBody(server, id, "application/json", bodyReader)
}

// NewUpdateZoneRequestWithBody generates requests for UpdateZone with any type of body
func NewUpdateZoneRequestWithBody(server string, id string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/zones/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PATCH", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewListApplicationsRequest generates requests for ListApplications
func NewListApplicationsRequest(server string, zoneId string, params *ListApplicationsParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "zoneId", runtime.ParamLocationPath, zoneId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/zones/%s/applications", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Slug != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "slug", runtime.ParamLocationQuery, *params.Slug); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Identifier != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "identifier", runtime.ParamLocationQuery, *params.Identifier); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Cursor != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "cursor", runtime.ParamLocationQuery, *params.Cursor); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateApplicationRequest calls the generic CreateApplication builder with application/json body
func NewCreateApplicationRequest(server string, zoneId string, body CreateApplicationJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateApplicationRequestWithBody(server, zoneId, "application/json", bodyReader)
}

// NewCreateApplicationRequestWithBody generates requests for CreateApplication with any type of body
func NewCreateApplicationRequestWithBody(server string, zoneId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "zoneId", runtime.ParamLocationPath, zoneId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/zones/%s/applications", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteApplicationRequest generates requests for DeleteApplication
func NewDeleteApplicationRequest(server string, zoneId string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "zoneId", runtime.ParamLocationPath, zoneId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/zones/%s/applications/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetApplicationRequest generates requests for GetApplication
func NewGetApplicationRequest(server string, zoneId string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "zoneId", runtime.ParamLocationPath, zoneId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/zones/%s/applications/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUpdateApplicationRequest calls the generic UpdateApplication builder with application/json body
func NewUpdateApplicationRequest(server string, zoneId string, id string, body UpdateApplicationJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpdateApplicationRequestWithBody(server, zoneId, id, "application/json", bodyReader)
}

// NewUpdateApplicationRequestWithBody generates requests for UpdateApplication with any type of body
func NewUpdateApplicationRequestWithBody(server string, zoneId string, id string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "zoneId", runtime.ParamLocationPath, zoneId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/zones/%s/applications/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PATCH", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewListProvidersRequest generates requests for ListProviders
func NewListProvidersRequest(server string, zoneId string, params *ListProvidersParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "zoneId", runtime.ParamLocationPath, zoneId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/zones/%s/providers", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Slug != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "slug", runtime.ParamLocationQuery, *params.Slug); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Identifier != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "identifier", runtime.ParamLocationQuery, *params.Identifier); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Type != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "type", runtime.ParamLocationQuery, *params.Type); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Cursor != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "cursor", runtime.ParamLocationQuery, *params.Cursor); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateProviderRequest calls the generic CreateProvider builder with application/json body
func NewCreateProviderRequest(server string, zoneId string, body CreateProviderJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateProviderRequestWithBody(server, zoneId, "application/json", bodyReader)
}

// NewCreateProviderRequestWithBody generates requests for CreateProvider with any type of body
func NewCreateProviderRequestWithBody(server string, zoneId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "zoneId", runtime.ParamLocationPath, zoneId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/zones/%s/providers", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteProviderRequest generates requests for DeleteProvider
func NewDeleteProviderRequest(server string, zoneId string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "zoneId", runtime.ParamLocationPath, zoneId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/zones/%s/providers/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetProviderRequest generates requests for GetProvider
func NewGetProviderRequest(server string, zoneId string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "zoneId", runtime.ParamLocationPath, zoneId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/zones/%s/providers/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUpdateProviderRequest calls the generic UpdateProvider builder with application/json body
func NewUpdateProviderRequest(server string, zoneId string, id string, body UpdateProviderJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpdateProviderRequestWithBody(server, zoneId, id, "application/json", bodyReader)
}

// NewUpdateProviderRequestWithBody generates requests for UpdateProvider with any type of body
func NewUpdateProviderRequestWithBody(server string, zoneId string, id string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "zoneId", runtime.ParamLocationPath, zoneId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/zones/%s/providers/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PATCH", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ListZonesWithResponse request
	ListZonesWithResponse(ctx context.Context, params *ListZonesParams, reqEditors ...RequestEditorFn) (*ListZonesResponse, error)

	// CreateZoneWithBodyWithResponse request with any body
	CreateZoneWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateZoneResponse, error)

	CreateZoneWithResponse(ctx context.Context, body CreateZoneJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateZoneResponse, error)

	// DeleteZoneWithResponse request
	DeleteZoneWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*DeleteZoneResponse, error)

	// GetZoneWithResponse request
	GetZoneWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetZoneResponse, error)

	// UpdateZoneWithBodyWithResponse request with any body
	UpdateZoneWithBodyWithResponse(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateZoneResponse, error)

	UpdateZoneWithResponse(ctx context.Context, id string, body UpdateZoneJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateZoneResponse, error)

	// ListApplicationsWithResponse request
	ListApplicationsWithResponse(ctx context.Context, zoneId string, params *ListApplicationsParams, reqEditors ...RequestEditorFn) (*ListApplicationsResponse, error)

	// CreateApplicationWithBodyWithResponse request with any body
	CreateApplicationWithBodyWithResponse(ctx context.Context, zoneId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateApplicationResponse, error)

	CreateApplicationWithResponse(ctx context.Context, zoneId string, body CreateApplicationJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateApplicationResponse, error)

	// DeleteApplicationWithResponse request
	DeleteApplicationWithResponse(ctx context.Context, zoneId string, id string, reqEditors ...RequestEditorFn) (*DeleteApplicationResponse, error)

	// GetApplicationWithResponse request
	GetApplicationWithResponse(ctx context.Context, zoneId string, id string, reqEditors ...RequestEditorFn) (*GetApplicationResponse, error)

	// UpdateApplicationWithBodyWithResponse request with any body
	UpdateApplicationWithBodyWithResponse(ctx context.Context, zoneId string, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateApplicationResponse, error)

	UpdateApplicationWithResponse(ctx context.Context, zoneId string, id string, body UpdateApplicationJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateApplicationResponse, error)

	// ListProvidersWithResponse request
	ListProvidersWithResponse(ctx context.Context, zoneId string, params *ListProvidersParams, reqEditors ...RequestEditorFn) (*ListProvidersResponse, error)

	// CreateProviderWithBodyWithResponse request with any body
	CreateProviderWithBodyWithResponse(ctx context.Context, zoneId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateProviderResponse, error)

	CreateProviderWithResponse(ctx context.Context, zoneId string, body CreateProviderJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateProviderResponse, error)

	// DeleteProviderWithResponse request
	DeleteProviderWithResponse(ctx context.Context, zoneId string, id string, reqEditors ...RequestEditorFn) (*DeleteProviderResponse, error)

	// GetProviderWithResponse request
	GetProviderWithResponse(ctx context.Context, zoneId string, id string, reqEditors ...RequestEditorFn) (*GetProviderResponse, error)

	// UpdateProviderWithBodyWithResponse request with any body
	UpdateProviderWithBodyWithResponse(ctx context.Context, zoneId string, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateProviderResponse, error)

	UpdateProviderWithResponse(ctx context.Context, zoneId string, id string, body UpdateProviderJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateProviderResponse, error)
}

type ListZonesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Items []Zone `json:"items"`

		// PageInfo Pagination information
		PageInfo PageInfo `json:"page_info"`
	}
	JSONDefault *Error
}

// Status returns HTTPResponse.Status
func (r ListZonesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListZonesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateZoneResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Zone
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r CreateZoneResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateZoneResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteZoneResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r DeleteZoneResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteZoneResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetZoneResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Zone
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r GetZoneResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetZoneResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UpdateZoneResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Zone
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r UpdateZoneResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpdateZoneResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListApplicationsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Items []Application `json:"items"`

		// PageInfo Pagination information
		PageInfo PageInfo `json:"page_info"`
	}
	JSONDefault *Error
}

// Status returns HTTPResponse.Status
func (r ListApplicationsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListApplicationsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateApplicationResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Application
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r CreateApplicationResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateApplicationResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteApplicationResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r DeleteApplicationResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteApplicationResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetApplicationResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Application
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r GetApplicationResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApplicationResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UpdateApplicationResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Application
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r UpdateApplicationResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpdateApplicationResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListProvidersResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Items []Provider `json:"items"`

		// PageInfo Pagination information
		PageInfo PageInfo `json:"page_info"`
	}
	JSONDefault *Error
}

// Status returns HTTPResponse.Status
func (r ListProvidersResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListProvidersResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateProviderResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Provider
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r CreateProviderResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateProviderResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteProviderResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r DeleteProviderResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteProviderResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetProviderResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Provider
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r GetProviderResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetProviderResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UpdateProviderResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Provider
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r UpdateProviderResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpdateProviderResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ListZonesWithResponse request returning *ListZonesResponse
func (c *ClientWithResponses) ListZonesWithResponse(ctx context.Context, params *ListZonesParams, reqEditors ...RequestEditorFn) (*ListZonesResponse, error) {
	rsp, err := c.ListZones(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListZonesResponse(rsp)
}

// CreateZoneWithBodyWithResponse request with arbitrary body returning *CreateZoneResponse
func (c *ClientWithResponses) CreateZoneWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateZoneResponse, error) {
	rsp, err := c.CreateZoneWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateZoneResponse(rsp)
}

func (c *ClientWithResponses) CreateZoneWithResponse(ctx context.Context, body CreateZoneJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateZoneResponse, error) {
	rsp, err := c.CreateZone(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateZoneResponse(rsp)
}

// DeleteZoneWithResponse request returning *DeleteZoneResponse
func (c *ClientWithResponses) DeleteZoneWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*DeleteZoneResponse, error) {
	rsp, err := c.DeleteZone(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteZoneResponse(rsp)
}

// GetZoneWithResponse request returning *GetZoneResponse
func (c *ClientWithResponses) GetZoneWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetZoneResponse, error) {
	rsp, err := c.GetZone(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetZoneResponse(rsp)
}

// UpdateZoneWithBodyWithResponse request with arbitrary body returning *UpdateZoneResponse
func (c *ClientWithResponses) UpdateZoneWithBodyWithResponse(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateZoneResponse, error) {
	rsp, err := c.UpdateZoneWithBody(ctx, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateZoneResponse(rsp)
}

func (c *ClientWithResponses) UpdateZoneWithResponse(ctx context.Context, id string, body UpdateZoneJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateZoneResponse, error) {
	rsp, err := c.UpdateZone(ctx, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateZoneResponse(rsp)
}

// ListApplicationsWithResponse request returning *ListApplicationsResponse
func (c *ClientWithResponses) ListApplicationsWithResponse(ctx context.Context, zoneId string, params *ListApplicationsParams, reqEditors ...RequestEditorFn) (*ListApplicationsResponse, error) {
	rsp, err := c.ListApplications(ctx, zoneId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListApplicationsResponse(rsp)
}

// CreateApplicationWithBodyWithResponse request with arbitrary body returning *CreateApplicationResponse
func (c *ClientWithResponses) CreateApplicationWithBodyWithResponse(ctx context.Context, zoneId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateApplicationResponse, error) {
	rsp, err := c.CreateApplicationWithBody(ctx, zoneId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateApplicationResponse(rsp)
}

func (c *ClientWithResponses) CreateApplicationWithResponse(ctx context.Context, zoneId string, body CreateApplicationJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateApplicationResponse, error) {
	rsp, err := c.CreateApplication(ctx, zoneId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateApplicationResponse(rsp)
}

// DeleteApplicationWithResponse request returning *DeleteApplicationResponse
func (c *ClientWithResponses) DeleteApplicationWithResponse(ctx context.Context, zoneId string, id string, reqEditors ...RequestEditorFn) (*DeleteApplicationResponse, error) {
	rsp, err := c.DeleteApplication(ctx, zoneId, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteApplicationResponse(rsp)
}

// GetApplicationWithResponse request returning *GetApplicationResponse
func (c *ClientWithResponses) GetApplicationWithResponse(ctx context.Context, zoneId string, id string, reqEditors ...RequestEditorFn) (*GetApplicationResponse, error) {
	rsp, err := c.GetApplication(ctx, zoneId, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApplicationResponse(rsp)
}

// UpdateApplicationWithBodyWithResponse request with arbitrary body returning *UpdateApplicationResponse
func (c *ClientWithResponses) UpdateApplicationWithBodyWithResponse(ctx context.Context, zoneId string, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateApplicationResponse, error) {
	rsp, err := c.UpdateApplicationWithBody(ctx, zoneId, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateApplicationResponse(rsp)
}

func (c *ClientWithResponses) UpdateApplicationWithResponse(ctx context.Context, zoneId string, id string, body UpdateApplicationJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateApplicationResponse, error) {
	rsp, err := c.UpdateApplication(ctx, zoneId, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateApplicationResponse(rsp)
}

// ListProvidersWithResponse request returning *ListProvidersResponse
func (c *ClientWithResponses) ListProvidersWithResponse(ctx context.Context, zoneId string, params *ListProvidersParams, reqEditors ...RequestEditorFn) (*ListProvidersResponse, error) {
	rsp, err := c.ListProviders(ctx, zoneId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListProvidersResponse(rsp)
}

// CreateProviderWithBodyWithResponse request with arbitrary body returning *CreateProviderResponse
func (c *ClientWithResponses) CreateProviderWithBodyWithResponse(ctx context.Context, zoneId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateProviderResponse, error) {
	rsp, err := c.CreateProviderWithBody(ctx, zoneId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateProviderResponse(rsp)
}

func (c *ClientWithResponses) CreateProviderWithResponse(ctx context.Context, zoneId string, body CreateProviderJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateProviderResponse, error) {
	rsp, err := c.CreateProvider(ctx, zoneId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateProviderResponse(rsp)
}

// DeleteProviderWithResponse request returning *DeleteProviderResponse
func (c *ClientWithResponses) DeleteProviderWithResponse(ctx context.Context, zoneId string, id string, reqEditors ...RequestEditorFn) (*DeleteProviderResponse, error) {
	rsp, err := c.DeleteProvider(ctx, zoneId, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteProviderResponse(rsp)
}

// GetProviderWithResponse request returning *GetProviderResponse
func (c *ClientWithResponses) GetProviderWithResponse(ctx context.Context, zoneId string, id string, reqEditors ...RequestEditorFn) (*GetProviderResponse, error) {
	rsp, err := c.GetProvider(ctx, zoneId, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetProviderResponse(rsp)
}

// UpdateProviderWithBodyWithResponse request with arbitrary body returning *UpdateProviderResponse
func (c *ClientWithResponses) UpdateProviderWithBodyWithResponse(ctx context.Context, zoneId string, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateProviderResponse, error) {
	rsp, err := c.UpdateProviderWithBody(ctx, zoneId, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateProviderResponse(rsp)
}

func (c *ClientWithResponses) UpdateProviderWithResponse(ctx context.Context, zoneId string, id string, body UpdateProviderJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateProviderResponse, error) {
	rsp, err := c.UpdateProvider(ctx, zoneId, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateProviderResponse(rsp)
}

// ParseListZonesResponse parses an HTTP response from a ListZonesWithResponse call
func ParseListZonesResponse(rsp *http.Response) (*ListZonesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListZonesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Items []Zone `json:"items"`

			// PageInfo Pagination information
			PageInfo PageInfo `json:"page_info"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseCreateZoneResponse parses an HTTP response from a CreateZoneWithResponse call
func ParseCreateZoneResponse(rsp *http.Response) (*CreateZoneResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateZoneResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Zone
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseDeleteZoneResponse parses an HTTP response from a DeleteZoneWithResponse call
func ParseDeleteZoneResponse(rsp *http.Response) (*DeleteZoneResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteZoneResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseGetZoneResponse parses an HTTP response from a GetZoneWithResponse call
func ParseGetZoneResponse(rsp *http.Response) (*GetZoneResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetZoneResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Zone
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseUpdateZoneResponse parses an HTTP response from a UpdateZoneWithResponse call
func ParseUpdateZoneResponse(rsp *http.Response) (*UpdateZoneResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpdateZoneResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Zone
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseListApplicationsResponse parses an HTTP response from a ListApplicationsWithResponse call
func ParseListApplicationsResponse(rsp *http.Response) (*ListApplicationsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListApplicationsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Items []Application `json:"items"`

			// PageInfo Pagination information
			PageInfo PageInfo `json:"page_info"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseCreateApplicationResponse parses an HTTP response from a CreateApplicationWithResponse call
func ParseCreateApplicationResponse(rsp *http.Response) (*CreateApplicationResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateApplicationResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Application
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseDeleteApplicationResponse parses an HTTP response from a DeleteApplicationWithResponse call
func ParseDeleteApplicationResponse(rsp *http.Response) (*DeleteApplicationResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteApplicationResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseGetApplicationResponse parses an HTTP response from a GetApplicationWithResponse call
func ParseGetApplicationResponse(rsp *http.Response) (*GetApplicationResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApplicationResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Application
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseUpdateApplicationResponse parses an HTTP response from a UpdateApplicationWithResponse call
func ParseUpdateApplicationResponse(rsp *http.Response) (*UpdateApplicationResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpdateApplicationResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Application
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseListProvidersResponse parses an HTTP response from a ListProvidersWithResponse call
func ParseListProvidersResponse(rsp *http.Response) (*ListProvidersResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListProvidersResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Items []Provider `json:"items"`

			// PageInfo Pagination information
			PageInfo PageInfo `json:"page_info"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseCreateProviderResponse parses an HTTP response from a CreateProviderWithResponse call
func ParseCreateProviderResponse(rsp *http.Response) (*CreateProviderResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateProviderResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Provider
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseDeleteProviderResponse parses an HTTP response from a DeleteProviderWithResponse call
func ParseDeleteProviderResponse(rsp *http.Response) (*DeleteProviderResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteProviderResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseGetProviderResponse parses an HTTP response from a GetProviderWithResponse call
func ParseGetProviderResponse(rsp *http.Response) (*GetProviderResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetProviderResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Provider
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseUpdateProviderResponse parses an HTTP response from a UpdateProviderWithResponse call
func ParseUpdateProviderResponse(rsp *http.Response) (*UpdateProviderResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpdateProviderResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Provider
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xc63LbNhZ+FQy3M2vvSrKbtju7/rPjJtmu26TxOM1kJhmvBiaPJDQkwAKgHTWjd98B",
	"wAtIglfJF7X6FSsEcICD79w+kPji+SyKGQUqhXf2xRP+CiKs/zyP45D4WBJG1c8AhM9JbH565xRZzxER",
	"CCPBFvIOc0BiLSRE6I7IFcIUYSGYT7CEAJEAqCRyjeQKS+Srh74PQqArECzhPogZupAowmuEfYnUyFIg",
	"dkfRDaxwuEBHEfZXhMJUsmn65zFiXLVMW7AFwigRwNFRACEstVwj5XjmTbyYsxi4JKAX6XNQDeZY1tf4",
	"0kxVN1GLlCQCIXEUexNvwXik+ngBljBVT7yJJ9cxeGeekJzQpbeZeAHEQAOgPgEx91lCHVJ+TqIb4Gra",
	"PNUBsrsVwxIqYQncjGuNUB3wv0mE6ZQDDvBNqAYrHk68CH9+BXQpV97Zs9Nv/znxaBKGqp13JnkCjjWQ",
	"oC7iHSW/JZDu5oKY6csVIGxhxjlW1sExptoyEYOvngfW2BOUGHEKT4RqOb8zCq7VRIRm//G1Q34EEgdY",
	"YiX9Kw4L78z7y0lhACcp+k9eZ+02E4/iCDqVrBuV5/Pdd53TYXyJKfldq2vu0vMbq4ExGXZHBZIrZW/t",
	"qo45k8xnoUY5DgKiGuLw0kL/AocCKmDyLtN+03QrfOQzuiDLhGeiqogpGxTDiVw961Kw5TvenKsOmVhv",
	"s8kXw25+BV+qxYgwWToQc/VqKvACBmPlH99UtybGUgJXg/7vI57+fjr91/Xfj/59Ns1/HP/tK5eWkzjo",
	"ch+myQjnoebtRMUHRqGGAXQDIaNLgSSrD7aZeBx+SwiHwDv7qEy6Dr5CYKrvkrmmduB0aRPbi5Z0cj3x",
	"JJEKKqVo4thh6/FzPVh92W81dtCC8dQl0yXCiMJdxRTKeCz50tqYL6ynbh9GJES6Y3lY175kMQyV9Fbb",
	"V/MfX7r36Nqhp/Q/MOd4/fCR4OC9mzxsT2eXubkU49VNTydiKdptQSjt325IFc86LA7ozujZ7BRl6xwY",
	"CDgEhIMv5wknDssrxs8aondXF0KbtyO+5WaY+86EE5d1NaA4NZiNW53FZHJtDVFt4bF2qGCtCdvBZ3mo",
	"90Q0PVKzY7D7ToeU+1awCVwPCWx0JEAiyZCSqMqYj9fqV0IFyONHQD16l6mgbW+2gn1Hftkf9VsmmpYH",
	"dulmGFq3wulQjfSE6Zb6SZfSqZ9eiCn00pjS6VXplI4i+EyE+bs1sTtkPk2ZT7Z5Tzb/6UBXM6hecs4c",
	"m6D/G3EQMaMC6iwPC1wpt1KsEHjpfiYklomwHlHN1NSStmyMiRGTd7RSNzNrx3JeWxs7wGWkpWUOi5pt",
	"MF/MEx46Ch7mJxFQmer56pVdjprgUgNnvVBpXMcoB1hZTS0oftmoXxwidgt5q+NOBzhACWWRdgTu0k2H",
	"63Dp6hIv4YIu2NAwgZeEpmwrNdNyuUWgwdxPuHBZyXP9/yhmhGr3Kpl2SiEWEqlUA6Veyk84BypRbGDd",
	"6R5XWMwpfJbzOLWlstj3K5ArUNkPcECYA4oYBy1RILyQ5lFVairlhrEQMM3ExBxuCUtEb1FGyg0slMhe",
	"YoTEXA7V4YLwrZRY8SlljbqWbnkXBSikEeVCG2e3JHAFrnOUPUvpe8Paa5pRJMobg8joeckKhh5hGiAc",
	"huxOPZaMC3SkgqBQtmp5cXGsuqksREVEH0tw0O8hASrd3GeenZpGZValE5PpyAJ8DuofB0F3QQM9LYHu",
	"UtjgTJbppvSS5WIQOMFy3+cHT5TnjzNUPcFk6akS9m06K+VSj0HIZ66gysZPPBYDNUvt1T8GevFiT9n8",
	"jJkFmkTKC8NnNQwOvYn3CdY+5sH0FiehtH6bCp/xtcXWPpnjgQxx93E2UKcqex0DXNaMoB6qhh8AWKa1",
	"o/jSHk96jJZGkKM7EoboBhBQn69jfRZNAyQk4xCoRgmHcH38+M7/D+uze5epGfy24ejzjKqZNmrwtC2I",
	"GknAK7/PeGbFQAOdszrYxO5cigUw91c4DIEuYR6BXLFAzFWSyLgEbVw5VTmQm5x4v959UnUaGTMzDksi",
	"JN9+icJnMexsSZJ9gm3ms3Egqt8ZhRtdTR61F0WeR5FGKrY30naMrAFIGo2cLZEyGBmjkDDY3TQRsl2A",
	"mKG3ZaIkZWVwGJppPUvbzw7u6c/unlpY3IZqoQ5H/Rw9Z5SCL8cGwkQAJ3TBdr3i8uR6eeXSehu9cp9V",
	"93TNfdY+fq19/E5pyY1+p8+SW52PGaCv83lYSPSwhC5M9Dkk7EbDNlxAlg5vxwg4jl1z7Q1AVReeOtTV",
	"hqS8XpjdK7VSHNFto07HOVpdnd3oG3s+u+O6u2FbZoP53p3X59vM7FDHP24d32YjzabxQSnAcWaiFKMN",
	"IuXIlBnw/Ggk1SCmyKbQ6ubh1tPzREgWoYBFmFCtJnT0/Ofz1y+P07eH8n3JQ9WKCdmgz7qJ/DnPKlKV",
	"7c05QdN8e5wRuN4cysYbE7qUEYw9EdB966cBNpWWTiIf8frw6n86tgA+z76VmmdR1omk3JXl2W+iIpcO",
	"2crhh2xJ6FjWv8z1FwDsRfV/KOG47FmHU/xOFD+OH31IT/cUAqrasD6keGXvW9J4h18Zx002eLdmbqlJ",
	"RqkHyntMOunAsigB/Bb43H5fr0nieUniW90RZe9R5TNAR7M7CMPpJ8ru6Il2mNOSyKkRedxjqoHP50AV",
	"YoLmN2derCmOiI+emzT5ymKwEBEo6+96F4IIkbgSz2LNpkX5pK1r1jb/Vh73x7dvfkbv4Qb9BGudnw/Y",
	"tviTD/MCwU3auPzp+Uu17KylAV1p53wWAFqE7E44lWK/Ld73ZfHiXfGqmxpKZjdJa9vlAVqsE4lNAnXL",
	"/kNXw5NBVpe1TZoMvzbTyr40adBCXxUyZXOqur5+hzV1N7jVQY0uTRq5n5r1L/SrDGng2bkzcBhYD4Hb",
	"2tumcx8GRaWxxyRZ5leEKHQUYy4JDtNHx937s9WGNCQW7Ru0ix3pEtxjh9qL8p2cGbQlD3m6XT5l6BJU",
	"HP2XBDUEcl3wTEsS+oRwJ2/dOq13AvgFXbDRvrdBHa651Lxg/xMSR445pMptd31ji10HWa3X1dOX9CWp",
	"x/iOXRDTjf6uecHtpjmWRu7nILcr9mqv+BsG97hnEfikWN6nVhQWZxkjiQvJCu6iQl00f5rR/3xOY7gJ",
	"upuJp2l+ItcapwZsN4A5cGUcxa//ZDj58f0vXjWD+fH9L+h73Qz9onPd8+LFd7PPWnM6FupmxUxWUsbe",
	"Rk2EpJ+FlIf+ybxris4vTWUQYYqXmd2Y1/HlCggveOiZVyze6u1NvFvgwox6OjudfZ3ReTgm3pn3zex0",
	"duppSmyltXCiJai/lq5DlSuQCacCYRQSIRFbpDPK7M5+9z+oMuLKtPXfF4F35r0iQn7QwpR4jiOQwIV3",
	"9vGLR5So3xLg64yKOsuIKQNG52UK7n7pVx0jeoYkIrLUMU9ovz491XZGoiTSv061maU/6/f3bK5VhDWf",
	"qmnlPjs9NV+pUQkmpFsfPp78KoxLKSRXrqLI3gPJ/+iyW9eLSTFewjzDX+vxSvb5Uq1I0+Ltkep87qbq",
	"Kb0XRovoKvt2T7dINTtAJ21TNp/fOYRXPhu0fYGGnu0FPl6rfRNJFGG+ThFr8K6MDS8VWD0D4WulTyYc",
	"FmMSBmFxmj2MZYbSYyeijB0RwULdBugt4YxGqhJQo1ycvy67gLKJGdkpK6s2DoT8ngXrnanZInY3G4OO",
	"LUDeDeL6fo48ntsXyBnl5gdEFcxtJqm/PvlCgo3BXgjOxBN4hNV8wzUybUSWaqbfdulr16x723IV1lD1",
	"QvdPUVXx3I7vEi5eeBPjX1WQKdyrPm4ovImJ6M1Ouu5Bv3Vd7rOnrsXotGmfJ+3BOACJSSjMPXj56y96",
	"c2/WRv/lHfwB5ONv38E3bImZH0A2AybG0l85TlF1SpzZ/l9FpRB1VGRl5Jj+jwKe+4leef17iF67R6hR",
	"bo/opf65CDYn1vyH1CB2t+xj7OK1p1R8vfqwv1y+3yKkdPy1pyVMJqJsyWbnHjQUbFML2XcSHkqiHZVE",
	"uGxHmZ2XzKtvgWTfCTNtuWG4+1rhhmqofCuly+Z3A/Ddh6v6hZn3HLVKxuIIXnt6IfSe1X6VW3/dxtUR",
	"S8fVh7Qi21UGPoA5uQPPoXysl4+9oDKqmLQNvbGm3F8sHHzmH8Rnqpq4pxV0VcilnapVypgG9mVsrip5",
	"r8zhXtOVhymyD6b3FIr9selKdnI8pO7P+wwo+i9zOU+44tfN7H6Yrt8s9CRrNxU5biEqWpUvMerVtO1+",
	"o+sDR3H/HEV+YdKBoNgRQRFbNp95pMIP9KUm8tdXpttdnVi5IrGBp7CuzdonkqJyo9c9h/zCVFzc+sNf",
	"drln1IJ9P6HDLNqi9MgTZ0uii024b9AfqIS+VEIHNEaRCLk9NjIIe7r/B4f2FOr+Tsh2nolnzcdU+/sD",
	"3fsL+g9T5x9sZKsCvSvo6yH5bYZefZ2+d6Jqv/8HAAD//zf6VHs6dAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
