name: 'Setup Test Environment'
description: 'Common setup for acceptance tests'
inputs:
  terraform_version:
    description: 'Terraform version to install (optional, uses latest if not specified)'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
      with:
        go-version-file: 'go.mod'
        cache: true
    - uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
      with:
        terraform_version: ${{ inputs.terraform_version && format('~{0}', inputs.terraform_version) || '' }}
        terraform_wrapper: false
    - run: go mod download
      shell: bash
